name: llmeval-trl24
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy=1.26.0
  - pandas=2.1.1
  - matplotlib=3.8.0
  - attrs=23.1.0
  - cattrs=23.1.2
  - tqdm=4.66.1
  - hydra-core=1.3.2
  - requests=2.31.0
  - tabulate=0.9.0
  - faker=28.4.1
  - tiktoken=0.7.0
  - jinja2=3.1.4